package httpproxy

import (
	"crypto/rand"
	"encoding/hex"
	"net"
	"net/http"
	"strings"
)

// requestIDHeader is the canonical correlation-id header nvelox stamps at the
// edge. It MUST stay exactly "X-Request-ID" so the id is read unchanged by every
// downstream service (the rest of the stack reads this same header name).
const requestIDHeader = "X-Request-ID"

// requestIDBytes matches the rest of the stack: 16 random bytes -> 32 hex chars,
// so an id generated at the gateway is byte-for-byte the same shape as one
// generated by any downstream service.
const requestIDBytes = 16

// maxInboundRequestIDLen bounds an inbound (attacker-influenceable) id before it
// is trusted, propagated upstream and written to the access log.
const maxInboundRequestIDLen = 128

// generateRequestID returns a fresh 32-hex-char correlation id.
func generateRequestID() string {
	b := make([]byte, requestIDBytes)
	if _, err := rand.Read(b); err != nil {
		// crypto/rand.Read does not fail on supported platforms; on the
		// impossible error we fall back to no id (logged as "-") rather than
		// emitting a predictable one.
		return ""
	}
	return hex.EncodeToString(b)
}

// isValidRequestID reports whether an inbound id is safe to trust and forward:
// non-empty, length-capped, and restricted to hex digits and dashes. This blocks
// CRLF / log-injection and oversized values that would otherwise ride the header
// to the backend and into the access log. The charset is permissive enough to
// accept both a bare 32-hex id and a dashed UUID from a trusted upstream.
func isValidRequestID(s string) bool {
	if len(s) == 0 || len(s) > maxInboundRequestIDLen {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= '0' && c <= '9',
			c >= 'a' && c <= 'f',
			c >= 'A' && c <= 'F',
			c == '-':
		default:
			return false
		}
	}
	return true
}

// resolveRequestID implements this listener's edge correlation-id policy. It
// returns the id to use and whether request-id handling is enabled at all.
//
// Trust model (mirrors setForwardedHeaders / realClientIP): at the true public
// edge an inbound X-Request-ID is attacker-controlled, so it is honored only
// when trust_inbound is set (internal listeners whose callers already carry an
// id) or the immediate connection peer is a configured trusted_proxy. Otherwise
// a fresh id is generated here, making this gateway the origin of truth for the
// trace so a request can be attributed to the gateway that first received it.
func (s *HTTPServer) resolveRequestID(r *http.Request) (string, bool) {
	if !s.Listener.RequestID.Enabled {
		return "", false
	}
	inbound := strings.TrimSpace(r.Header.Get(requestIDHeader))
	if inbound != "" && isValidRequestID(inbound) {
		if s.Listener.RequestID.TrustInbound {
			return inbound, true
		}
		if peer, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
			if ip := net.ParseIP(peer); ip != nil && s.ipTrusted(ip) {
				return inbound, true
			}
		}
	}
	return generateRequestID(), true
}
